version: 2.1
jobs:
  build-and-scrape:
    working_directory: ~/project/RPScraper
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          command: |
            cd RPScraper
            chmod u+x scripts/build_and_scrape.sh
            ./scripts/build_and_scrape.sh
  upload-data:
    working_directory: ~/project/RPScraper
    docker:
      - image: circleci/python:3.7.2
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run:
          command: |
            cd RPScraper
            chmod u+x scripts/upload_data.sh
            ./scripts/upload_data.sh

orbs:
  aws-cli: circleci/aws-cli@1.0.0
workflows:
  version: 2.1
  daily-update:
    jobs:
      - build-and-scrape
      - upload-data:
          requires:
            - build-and-scrape
          context: aws
#    triggers:
#      - schedule:
#          cron: "0 0 * * *"
#          filters:
#            branches:
#              only:
#                - master
