version: 2.1

jobs:
  build-and-scrape:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          command: |
            # Setup environment, install dependencies
            sudo apt-get install bsdmainutils
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            # Unencrypt files
            git clone https://github.com/elasticdog/transcrypt.git
            cd transcrypt
            sudo ln -s ${PWD}/transcrypt /usr/local/bin/transcrypt
            cd ..
            transcrypt -c $TRANSCRYPT_CIPHER -p $TRANSCRYPT_PASSWORD -y -F
            # Run daily updates
            chmod u+x run_daily_updates.sh
            chmod u+x run_rpscrape_script.sh
            date=$(date +%Y/%m/%d -d "yesterday")
            echo "Running rpscrape for date: $date"
            countries=("gb" "ire")
            ./run_daily_updates.sh $countries $date
  upload-data:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run:
          command: |
            chmod u+x upload_daily_updates.sh
            ./upload_daily_updates.sh

orbs:
  aws-cli: circleci/aws-cli@1.0.0
workflows:
  version: 2.1
  daily-update:
    jobs:
      - build-and-scrape
      - upload-data:
          requires:
            - build-and-scrape
          context: aws
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
