version: 2.1
jobs:
  build-and-scrape:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          command: |
            chmod u+x build_and_scrape.sh
            ./build_and_scrape.sh
  upload-data:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run:
          command: |
            python src/upload_data_to_s3.py

orbs:
  aws-cli: circleci/aws-cli@1.0.0
workflows:
  version: 2.1
  daily-update:
    jobs:
      - build-and-scrape
      - upload-data:
          requires:
            - build-and-scrape
          context: aws
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
